version: "3.8"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
      # Only build development stage form Dockerfile
      target: development
    # Mount our host dir to the docker container
    # Mount api directory (./api) to (:) docker container (/api/src/app)
    # Reflect File changes from host to container
    volumes:
      - ./api:/ait/src/app
      - ./ait/src/app/node_modules
    # RUN in debug mode: npm run start:debug => also start your vscode debugger
    # RUN in dev mode: npm run start:dev 
    command: npm run start:dev
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - 3000:3000
      - 9229:9229

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
      target: development
    command: npm run start
    volumes:
      - ./frontend:/ait/frontend/src/app
      - /ait/frontend/src/app/node_modules
    ports:
      - 4200:4200
    links: 
      - api

  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passsword
      POSTGRES_DB: db
    ports:
      - 35000:5432
  
  postgres_admin:
    image: dpage/pgadmin4:4.28
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: passsword
    ports:
      - 5050:80